name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: jebashinba/selenium-test:latest

    # Step 3: Configure kubeconfig
    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    # Step 4: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/my-deployment my-container=jebashinba/selenium-test:latest
        kubectl rollout status deployment/my-deployment

