name: CI/CD with Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Configure kubectl
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    # Debug kubectl context
    - name: Debug kubectl context
      run: kubectl config view

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yml --validate=false
        kubectl rollout status deployment/my-app
