name: Create Kubernetes Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl

          # Add the Kubernetes APT repository for the current Ubuntu version (Jammy)
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-apt main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

          # Update the package list and install Docker and Kubernetes
          sudo apt-get update
          sudo apt-get install -y docker.io kubelet kubeadm kubectl

      - name: Initialize Kubernetes Cluster
        run: kubeadm init --pod-network-cidr=192.168.0.0/16

      - name: Configure Kubectl
        run: |
          mkdir -p $HOME/.kube
          sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
