name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest ghcr.io/owner/my-app:latest
          docker push ghcr.io/owner/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/my-app

      - name: Run Integration Tests
        run: |
          kubectl apply -f k8s/test-deployment.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/test
          kubectl logs deployment/test
