name: Lint Kubernetes Configurations

on:
  push:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install kube-linter
      run: |
        # Fetch the latest kube-linter release URL
        curl -s https://api.github.com/repos/stackrox/kube-linter/releases/latest | \
        grep "browser_download_url.*linux" | \
        cut -d : -f 2,3 | tr -d '"' | wget -qi -
        # Identify the downloaded tar.gz file
        echo "Downloaded files:"
        ls -la
        FILE=$(ls kube-linter-*.tar.gz | head -n 1)
        echo "Extracting: $FILE"
        # Extract the tarball
        tar -xzf "$FILE"
        chmod +x kube-linter
        sudo mv kube-linter /usr/local/bin/
        # Clean up
        rm -f kube-linter-*.tar.gz

    - name: Verify kube-linter installation
      run: |
        kube-linter version

    - name: Validate Kubernetes manifests
      run: |
        kube-linter lint manifests/

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get
