name: Lint Kubernetes Configurations

on:
  push:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install kube-linter
      run: |
        # Fetch the latest kube-linter release URL
        curl -s https://api.github.com/repos/stackrox/kube-linter/releases/latest | \
        grep "browser_download_url.*linux" | \
        cut -d : -f 2,3 | tr -d '"' | wget -qi -
        # Identify the downloaded tar.gz file
        echo "Downloaded files:"
        ls -la
        FILE=$(ls kube-linter-*.tar.gz | head -n 1)
        echo "Extracting: $FILE"
        # Extract the tarball
        tar -xzf "$FILE"
        chmod +x kube-linter
        sudo mv kube-linter /usr/local/bin/
        # Clean up
        rm -f kube-linter-*.tar.gz

    - name: Verify kube-linter installation
      run: |
        kube-linter version

    - name: Validate Kubernetes k8s
      run: |
          # Verify that the directory exists
          if [ -d "k8s" ]; then
            kube-linter lint k8s/
          else
            echo "Error: 'k8s/' directory not found. Skipping kube-linter lint."
            exit 1
          fi
  
    - name: Install Helm
      run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: List files in k8s directory
      run: |
        echo "Listing files in the 'k8s' directory:"
        ls -R k8s

    - name: Rename chart.yaml to Chart.yaml
      run: |
          mv k8s/chart.yaml k8s/Chart.yaml
          echo "Renamed chart.yaml to Chart.yaml"


    
    - name: Check for chart.yaml
      run: |
        if [ -f "k8s/Chart.yaml" ]; then
          echo "'chart.yaml' found in 'k8s'. Renaming it to 'Chart.yaml'..."
        else
          echo "Error: 'chart.yaml' file not found. Exiting process."
          exit 1
        fi
    - name: Run yamllint on k8s resources
      run: |
          echo "Running yamllint on Kubernetes YAML files..."
          sudo apt-get install -y yamllint
          yamllint k8s/**/*.yaml
          echo "YAML linting complete"
  
    - name: Check Helm Chart Validity
      run: |
          if helm lint ./k8s; then
            echo "Helm chart is valid."
          else
            echo "Helm chart is invalid. Please review the error message."
            exit 1
          fi
  
    - name: Helm Template Rendering
      run: |
          echo "Rendering Helm templates..."
          helm template ./k8s
          echo "Template rendering complete"
  
    - name: Test Helm Upgrade (optional)
      run: |
          echo "Testing Helm upgrade with the current chart version..."
          helm upgrade --install myapp ./k8s --dry-run
          echo "Helm upgrade dry-run complete"
    - name: Lint Helm chart
      run: |
          echo "Linting Helm chart..."
          helm lint ./k8s